Repository GBTeamworks/gift_service, pull requests merged in 2022-11, with the labels that each got.

#2 add gitignore and readme
  .gitignore
  README.md
Labels: documentation

#10 Добавлен стек Новиковой Е. + ТЗ
  README.md
  ТЗ.docx
Labels: documentation

#11 Create base project
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  HELP.md
  docker-compose.yml
  gift_service.iml
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/giftservice/gift_service/GiftServiceApplication.java
  src/main/resources/application.properties
  src/main/resources/db/migration/.gitkeep
  src/main/resources/static/.gitkeep
  src/main/resources/templates/.gitkeep
  src/test/java/com/giftservice/gift_service/GiftServiceApplicationTests.java
Labels: enhancement

#19 MariaDB, Flyway and Docker configured
  Dockerfile
  docker-compose.yml
  gift_service.iml
  pom.xml
  src/main/resources/application.properties
  src/main/resources/db/migration/V1__Init_DB.sql
  src/test/java/com/giftservice/gift_service/GiftServiceApplicationTests.java
Labels: enhancement

#21 readme ready
  README.md
  gift_service.iml
Labels: documentation

#22 MainController, index page, mariadb 10.6
  docker-compose.yml
  gift_service.iml
  src/main/java/com/giftservice/gift_service/controllers/MainController.java
  src/main/resources/templates/.gitkeep
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
Labels: enhancement

#26 добавил компетенции
  README.md
Labels: documentation

#28 Issue 27 Добавление маппингов и кнопок Войти и Регистрация
  src/main/java/com/giftservice/gift_service/controllers/MainController.java
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/gifts.html
  src/main/resources/templates/login.html
  src/main/resources/templates/registration.html
  src/main/resources/templates/users.html
  src/main/resources/templates/wishes.html
Labels: enhancement

#25 Добавлены сущности User, Gift + описание в бд
  src/main/java/com/giftservice/gift_service/entities/Gift.java
  src/main/java/com/giftservice/gift_service/entities/User.java
  src/main/resources/db/migration/V1__Init_DB.sql
Labels: enhancement

#29 Sprint 02
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  Dockerfile
  HELP.md
  README.md
  docker-compose.yml
  gift_service.iml
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/giftservice/gift_service/GiftServiceApplication.java
  src/main/java/com/giftservice/gift_service/controllers/MainController.java
  src/main/java/com/giftservice/gift_service/entities/Gift.java
  src/main/java/com/giftservice/gift_service/entities/User.java
  src/main/resources/application.properties
  src/main/resources/db/migration/.gitkeep
  src/main/resources/db/migration/V1__Init_DB.sql
  src/main/resources/static/.gitkeep
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/gifts.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/registration.html
  src/main/resources/templates/users.html
  src/main/resources/templates/wishes.html
  src/test/java/com/giftservice/gift_service/GiftServiceApplicationTests.java
  ТЗ.docx
Labels: sprint close
