Repository GBTeamworks/gift_service, pull requests merged in 2022-12, with the labels that each got.

#51 Добавление Spring Security и авторизация через БД
  pom.xml
  src/main/java/com/giftservice/gift_service/config/SecurityConfig.java
  src/main/java/com/giftservice/gift_service/controllers/MainController.java
  src/main/java/com/giftservice/gift_service/dao/AuthorityDao.java
  src/main/java/com/giftservice/gift_service/dao/UserDao.java
  src/main/java/com/giftservice/gift_service/entities/Gift.java
  src/main/java/com/giftservice/gift_service/entities/User.java
  src/main/java/com/giftservice/gift_service/entities/security/Authority.java
  src/main/java/com/giftservice/gift_service/entities/security/User.java
  src/main/java/com/giftservice/gift_service/security/JpaUserDetailService.java
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/login.html
Labels: enhancement

#48 Issue 38. CartController + CRUD
  src/main/java/com/giftservice/gift_service/controllers/CartController.java
  src/main/java/com/giftservice/gift_service/entities/Cart.java
  src/main/java/com/giftservice/gift_service/entities/Gift.java
  src/main/java/com/giftservice/gift_service/entities/enums/Status.java
  src/main/resources/db/migration/V1__Init_DB.sql
  src/main/resources/templates/cart.html
Labels: enhancement

#52 Исправления с 3-го урока
  docker-compose.yml
  pom.xml
  src/main/resources/application.properties
Labels: bugfix

#53 Issue 36
  src/main/java/com/giftservice/gift_service/controllers/GiftController.java
  src/main/java/com/giftservice/gift_service/dao/GiftDao.java
  src/main/java/com/giftservice/gift_service/entities/Gift.java
  src/main/java/com/giftservice/gift_service/services/GiftService.java
Labels: enhancement

#55 Issue 43
  src/main/resources/static/index.html
  src/main/resources/static/index.js
  src/main/resources/static/personalAccount/personalAccount.html
  src/main/resources/static/personalAccount/personalAccount.js
  src/main/resources/static/registration/registration.html
  src/main/resources/static/registration/registration.js
Labels: frontend
